### ISSUE TITLE
Does not work on windows: ValueError: Invalid format string

### ISSUE THREAD

**Issue by amkartashov** [Osndok/zim-plugin-nowbutton#2]
%n and %P are unix-specific, see [strftime.org](http://strftime.org/)

I replaced line 94 with

> text='\n' + strftime('%I:%M%p - ');

to fix this.

Exception reported by Zim below.

> This is zim 0.65
> Platform: nt
> Locale: en_US cp1252
> FS encoding: mbcs
> Python: (2, 7, 11, 'final', 0)
> Gtk: (2, 24, 10)
> Pygtk: (2, 24, 0)
> Zim revision is:
>   branch: 065
>   revision: 805 jaap.karssenberg@gmail.com-20151101144245-0g7s8a7qjt5xu1d0
>   date: 2015-11-01 15:42:45 +0100
> 
> ======= Traceback =======
>   File "zim\actions.pyo", line 109, in func
>   File "C:\Users\me\Config\zim\data\zim\plugins\nowbutton.py", line 94, in now_button_clicked
> ValueError: Invalid format string

**Comment by Osndok** [comment]
Thanks gorilych, I've applied the change, but added a '.lower()' so maintain the desired effect (i.e. a lowercase am/pm indicator).
