### ISSUE TITLE
New version with path-name from Journal options do not work

### ISSUE THREAD

**Issue by Nick222** [Osndok/zim-plugin-nowbutton#6]
Xubuntu 17.10-64
UTF-8
zim-plugin-nowbutton from this repository
Journal path-name in Russian

When I push "Now" button I see window with error message:

"This is zim 0.67
Platform: posix
Locale: ru_RU UTF-8
FS encoding: UTF-8
Python: (2, 7, 14, 'final', 0)
Gtk: (2, 24, 31)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 157, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/home/nick/.local/share/zim/plugins/nowbutton.py", line 89, in now_button_clicked
    path=ui.notebook.pages.lookup_from_user_input(name);
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/pages.py", line 652, in lookup_from_user_input
    source, href, ignore_link_placeholders=False)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/pages.py", line 325, in resolve_link
    return self.resolve_pagename(ROOT_PATH, href.parts())
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/pages.py", line 405, in resolve_pagename
    page_id, pagename, branch = self._resolve_pagename(parent, names)
  File "/usr/lib/python2.7/dist-packages/zim/notebook/index/pages.py", line 430, in _resolve_pagename
    (basename,)
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings."

**Comment by Osndok** [comment]
This is the logical continuation of https://github.com/jaap-karssenberg/zim-desktop-wiki/issues/272

I think the problem is on line 79: https://github.com/Osndok/zim-plugin-nowbutton/blob/master/nowbutton.py#L79 ... but ATM, I'm not sure what to replace 'str()' with to be unicode-friendly.

**Comment by Nick222** [comment]
May be it is know-how (from https://habrahabr.ru/post/135913/):

Do not use «str» and Unicode, because «str» cannot define codepage and it use ASCII - and it lead to error:

> print type(s), s
<type 'unicode'> кощей
> str(s)

Traceback (most recent call last):

>   File "<pyshell#90>", line 1, in <module>
>     str(s)
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
> 

Use «encode»:

> s = s.encode('cp1251')
> print type(s), s
<type 'str'> кощей

**Comment by Osndok** [comment]
It may be as simple as replacing 'str(...)' with 'unicode(...)' or "(...).encode('utf-8')", I just don't know which is better, and I don't have the time at the moment to figure out which ones work.

**Comment by Osndok** [comment]
...or there could be a method to return the page path without using a conversion, but I forget which python class is being converted to a string (python has kinda loose typing).
